In [1]:
import pandas as pd

In [2]:
pd.read_csv("../input/students.csv")

    张祥德  RB17101  RB171  男  1997-02-10  11122223333  河南省郑州市1号  88
0   冯成刚  RB17102  RB171  女  1996-10-01  18837110115  河南省洛阳市2号  86
1   卢伟兴  RB17103  RB171  男  1998-08-02  19999228822  河南省开封市3号  95
2   杨飞龙  RB17104  RB171  男  1996-08-09  13322554455  河南省安阳市4号  91
3   姜松林  RB17201  RB172  女  1997-01-03  13688552244  河南省鹤壁市1号  75
4    高飞  RB17202  RB172  男  1996-08-27  13522114455  河南省新乡市2号  68
5    何桦  RB17203  RB172  女  1997-12-20  13566998855  河南省焦作市3号  84
6   高天阳  RB17204  RB172  男  1999-11-08  13688446622  河南省濮阳市4号  77
7   周存富  RB17301  RB173  男  1996-05-28  13699552658  河南省许昌市1号  93
8    罗鹏  RB17302  RB173  男  1998-03-02  13365298741  河南省漯河市2号  85
9   宋立昌  RB17401  RB174  男  1995-05-28  13596325874  河南省南阳市3号  81
10  杨国胜  RB17402  RB174  男  1996-03-02  13256987456  河南省信阳市4号  91
11  徐子文  RB17403  RB174  男  1998-05-28  13523654789  河南省周口市5号  85
12   马彦  RB17404  RB174  女  1997-03-02  13526845962  河南省郑州市6号  73

In [9]:
data = pd.read_json("../input/students2.json")
data

   name       no    cls gender    birthday        phone       loc
0   张祥德  RB17101  RB171      男  1997-02-10  11122223333  河南省郑州市1号
1   冯成刚  RB17102  RB171      女  1996-10-01  18837110115  河南省洛阳市2号
2   卢伟兴  RB17103  RB171      男  1998-08-02  19999228822  河南省开封市3号
3   杨飞龙  RB17104  RB171      男  1996-08-09  13322554455  河南省安阳市4号
4   姜松林  RB17201  RB172      女  1997-01-03  13688552244  河南省鹤壁市1号
5    高飞  RB17202  RB172      男  1996-08-27  13522114455  河南省新乡市2号
6    何桦  RB17203  RB172      女  1997-12-20  13566998855  河南省焦作市3号
7   高天阳  RB17204  RB172      男  1999-11-08  13688446622  河南省濮阳市4号
8   周存富  RB17301  RB173      男  1996-05-28  13699552658  河南省许昌市1号
9    罗鹏  RB17302  RB173      男  1998-03-02  13365298741  河南省漯河市2号
10  宋立昌  RB17401  RB174      男  1995-05-28  13596325874  河南省南阳市3号
11  杨国胜  RB17402  RB174      男  1996-03-02  13256987456  河南省信阳市4号
12  徐子文  RB17403  RB174      男  1998-05-28  13523654789  河南省周口市5号
13   马彦  RB17404  RB174      女  1997-03-02  13526845962  河南省郑州市6号

In [7]:
data.to_json("../input/students3.json")

In [8]:
data = pd.read_orc("../input/students.orc")
data

ArrowException: Unknown error: Time zone file /usr/share/zoneinfo/UTC does not exist. Please install IANA time zone database and set TZDIR env.

In [10]:
data.to_orc("../input/students2.orc")

In [11]:
data = pd.read_parquet("../input/students.parquet")
data

   name       no    cls gender    birthday        phone       loc
0   张祥德  RB17101  RB171      男  1997-02-10  11122223333  河南省郑州市1号
1   冯成刚  RB17102  RB171      女  1996-10-01  18837110115  河南省洛阳市2号
2   卢伟兴  RB17103  RB171      男  1998-08-02  19999228822  河南省开封市3号
3   杨飞龙  RB17104  RB171      男  1996-08-09  13322554455  河南省安阳市4号
4   姜松林  RB17201  RB172      女  1997-01-03  13688552244  河南省鹤壁市1号
5    高飞  RB17202  RB172      男  1996-08-27  13522114455  河南省新乡市2号
6    何桦  RB17203  RB172      女  1997-12-20  13566998855  河南省焦作市3号
7   高天阳  RB17204  RB172      男  1999-11-08  13688446622  河南省濮阳市4号
8   周存富  RB17301  RB173      男  1996-05-28  13699552658  河南省许昌市1号
9    罗鹏  RB17302  RB173      男  1998-03-02  13365298741  河南省漯河市2号
10  宋立昌  RB17401  RB174      男  1995-05-28  13596325874  河南省南阳市3号
11  杨国胜  RB17402  RB174      男  1996-03-02  13256987456  河南省信阳市4号
12  徐子文  RB17403  RB174      男  1998-05-28  13523654789  河南省周口市5号
13   马彦  RB17404  RB174      女  1997-03-02  13526845962  河南省郑州市6号

In [12]:
data.to_parquet("../input/students2.parquet")